#!/bin/bash
#------------------------------------------------------------------------------
# darcyBrinkmanBRNSFoam box1D tutorial - Allclean
#------------------------------------------------------------------------------
cd "${0%/*}" || exit 1
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions

cleanCase
rm -rf constant/polyMesh

#------------------------------------------------------------------------------
