#!/bin/bash
#------------------------------------------------------------------------------
# BRNSFoam applications build script
#------------------------------------------------------------------------------
cd "${0%/*}" || exit 1

set -e

echo "Building solvers..."
(cd solvers && ./Allwmake)

echo "Applications built successfully."

#------------------------------------------------------------------------------
